apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "..fullname" . }}-keygen
  labels:
  {{- include "..labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
